### ISSUE TITLE
git-review reset should delete .git/rebase-gerrit

### ISSUE THREAD

**Issue by indirect** [indirect/gerrit-tools#1]
gerrit-cherry-pick leaves a .git/rebase-gerrit file lying around if the cherry-pick fails. `git review reset` should take care of that so I don't have to keep deleting it by hand.

**Comment by eventualbuddha** [comment]
Fixed in [this commit](http://github.com/indirect/gerrit-tools/commit/6e630003ce1145e5bbfb7c3d1787852062898069).
