### ISSUE TITLE
do you know this error's reason.

### ISSUE THREAD

**Issue by xiaods** [indirect/gerrit-tools#3]
~ ⮁gerrit-cherry-pick --continue
Applying: fix the board list page. refine for add list.
/home/dxiao/local/bin/gerrit-cherry-pick: line 52: get_changeid: command not found
/home/dxiao/local/bin/gerrit-cherry-pick: line 57: .git/GERRIT_CHANGES/: Is a directory
Done.

**Comment by indirect** [comment]
Sorry, I don't.

**Comment by xiaods** [comment]
@indirect thanks a lot.maybe this is Environment case. ignore it.
