### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by bfontaine** [indirect/gerrit-tools#4]
Hello,

I know this project hasn’t been updated in a long time, but would it be possible to have a tagged release? This would allow us to download the tools as an archive and ensure we always get the same code.

Something like the following should suffice (you can change the version):

``` sh
git tag v1.0.0
git push --tags origin master
```

Thanks!

**Comment by indirect** [comment]
Sure, why not. Done.

**Comment by bfontaine** [comment]
Thanks!
